
#!/usr/bin/env bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
subscription='af10f960-61a9-4c1c-a9a9-2abb2ea1629b'
resource_group='mlinsights'
aml_workspace='mlinsights'

resource="/subscriptions/${subscription}/resourceGroups/${resource_group}/providers/Microsoft.MachineLearningServices/workspaces/${aml_workspace}"
log_analytics_workspace='/subscriptions/af10f960-61a9-4c1c-a9a9-2abb2ea1629b/resourcegroups/mlinsights/providers/microsoft.operationalinsights/workspaces/mlanalytics'
az monitor diagnostic-settings create -n SendAllToLogAnalytics --resource $resource --workspace $log_analytics_workspace --logs '[{"category":"AmlComputeClusterEvent","enabled":true},{"category":"AmlComputeClusterNodeEvent","enabled":true},{"category":"AmlComputeJobEvent","enabled":true},{"category":"AmlComputeCpuGpuUtilization","enabled":true},{"category":"AmlRunStatusChangedEvent","enabled":true},{"category":"ModelsChangeEvent","enabled":true},{"category":"ModelsReadEvent","enabled":true},{"category":"ModelsActionEvent","enabled":true},{"category":"DeploymentReadEvent","enabled":true},{"category":"DeploymentEventACI","enabled":true},{"category":"DeploymentEventAKS","enabled":true},{"category":"InferencingOperationAKS","enabled":true},{"category":"InferencingOperationACI","enabled":true},{"category":"EnvironmentChangeEvent","enabled":true},{"category":"EnvironmentReadEvent","enabled":true},{"category":"DataLabelChangeEvent","enabled":true},{"category":"DataLabelReadEvent","enabled":true},{"category":"ComputeInstanceEvent","enabled":true},{"category":"DataStoreChangeEvent","enabled":true},{"category":"DataStoreReadEvent","enabled":true},{"category":"DataSetChangeEvent","enabled":true},{"category":"DataSetReadEvent","enabled":true},{"category":"PipelineChangeEvent","enabled":true},{"category":"PipelineReadEvent","enabled":true},{"category":"RunEvent","enabled":true},{"category":"RunReadEvent","enabled":true}]' --metrics '[{"category":"AllMetrics","Enabled":true}]'